Create table sample_equipment
(
Category varchar2(4000),	
Subcategory	varchar2(4000),
NameE 	varchar2(4000),
Quantity varchar2(4000),	
Price	varchar2(4000),
CostV	varchar2(4000),
Comments varchar2(4000),	
Scalable	varchar2(4000),
QtyPerPerson	varchar2(4000),
SortOrder	varchar2(4000),
Platter varchar2(4000),
Active varchar2(4000)
);


REM INSERTING into SAMPLE_EQUIPMENT
SET DEFINE OFF;
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Dinner Forks, Silverware','286','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Dinner Knife, Stainless Steel','850','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Fork Medium, Stainless Steel','140','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Knife Medium, Stainless Steel','800','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Medium Forks, Silverware','410','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Medium Knives, Silverware','1100','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Teaspoon, Silverware','470','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Teaspoon, Stainless Steel','170','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','All Purpose ','985','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Champagne ','338','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Cordial ','136','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Highball','525','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Martini Tall','80','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Martini, Stemless ','105','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Old Fashioned','1408','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Red Wine','532','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Rocks, Sterling','380','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Shot','94','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Shot with Base','195','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','Water','1777','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Glassware','White Wine','711','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Kitchen Equipment','Carrier ','26','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Kitchen Equipment','Ice Tubs','67','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Kitchen Equipment','Stainless Steel Full Pan Inserts','18','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Kitchen Equipment','Stainless Steel Half Pan Inserts','25','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Bowl, Ceramic Wavy, 2 Qt','15','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Bowl, Ceramic White 14"','31','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Finger Bowls, Glass','48','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Plates, Glass Amber 16"','95','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Salad Scissors  ','123','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Sauce Bowl, Glass 16oz','12','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Sauce Bowl, Glass 6oz','12','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Serving Spoon, Silverware','27','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Soup Ladles, Silverware','36','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Spatula, Silverware','28','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Spatula, Stainless Steel','8','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Tongs, Medium','24','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Serviceware','Tray, Silver Pick Up','113','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Tables','Cabaret','57','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Tables','Round 3''','11','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Beverage Bervice','Cambro, Beverage','12','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Flatware','Medium Knife, Silverware','180','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Flatware','Teaspoon, Silverware','80','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Glassware','All Purpose Glass','158','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Glassware','Old Fashion Highball','125','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Black, 108"','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Blush, 132"','31','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Cherry, 108"','37','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Hunter Green, 108"','24','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Ivory, 108"','18','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Navy Ridgeline, 108"','8','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Navy, 108"','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Raffia Eudoro, 132"','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Round, 108"','8','0.0','0.0','Sales person to select color',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Royal Blue Twill, 132"','10','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','Royal Blue, 108"','21','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Linen','White Ridgeline, 108"','26','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Serviceware','Tong (For Ice + Salad)','19','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Serviceware','Serving Fork','4','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Serviceware','Serving Spoon','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Serviceware','Tray, Large Round Pick Up','8','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Serviceware','Tray, Vegetable Round','3','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Tables','Cabaret','4','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Tables','Round 3''','4','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Tables','Serpentine','2','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Buffet Equipment','Chafer, 4 Qt','22','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Buffet Equipment','Sterno Grill ','5','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','China','Coffee Cup','192','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','China','Coffee Saucer','69','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','China','Plate, B/B','475','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','China','Plate, Dinner 10"','270','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','China','Plate, Salad 7"','240','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','China','Soup Bowl','160','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Coffee Service','Samovar, Silver','9','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Flatware','Dessert Spoons','100','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Flatware','Dinner Forks','153','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Flatware','Dinner Knives','230','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Flatware','Salad Forks','100','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Glassware','Highball','588','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Glassware','Red Wine','176','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Glassware','Water','266','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Glassware','White Wine','352','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Kitchen Equipment','Cambro, Hot Food','4','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Kitchen Equipment','Crescor','5','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Kitchen Equipment','Speed Racks','20','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Baby Blue Pintuck, 132"','22','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Beaumont Damask White, 132"','33','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Blue Periwinkle, 132"','11','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Blue Troy, 142"','30','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Burgandy, 142"','35','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Burgandy Pintuck, 132"','10','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Burnt Orange, 142"','20','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Cele Don Green, 120"','10','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Cranberry Damask, 132"','54','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Forest Green, 142"','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Gold Satin, 120"','14','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Ivory, 142"','46','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Ivory Pintuck, 132"','10','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Mocha Pintuck, 132"','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Royal Blue, 132"','13','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Sage Green, 142"','40','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Sage Pintuck, 142"','54','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Seafoam Twill, 132"','5','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Victorian Gold Satin, 142"','13','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Wedgewood Blue Twill, 132"','14','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','White Melody, 142"','45','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','White Napkins','200','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Linen','Willow Green, 132"','15','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Service Equipment','Plate Cover','240','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Serviceware','Dressing Ladles','100','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Serviceware','Spatulas','100','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Tables','Rectangle 6''','3','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Tables','Round 3''','5','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Tables','Round 5''','2','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('NEA','Tables','Serpentine','3','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Baskets','Basket, Large Metal','4','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Baskets','Bread Basket, Wire','2','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Beverage Service','Pitcher, Plastic Clear','18','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Buffet Equipment','Electric Chafers','8','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','China','Boullion Saucers','180','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','China','Coffee Cups','120','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','China','Coffee Saucer','90','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','China','Plate, Diner','180','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','China','Plate, Salad','120','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','China','Plate, Tea','120','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Coffee Service','Coffee Airpot','12','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Coffee Service','Coffee Pot','3','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Coffee Service','Plug in Coffee Maker','4','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Flatware','Boullion Spoon, Silverware','20','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('PENTAGON','Flatware','Medium Forks, Silverware','150','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Baskets','Basket, Wire','45','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Baskets','Basket, Wire Small','12','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Baskets','Bread Basket, Oval Wire Small','182','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Beverage Dispenser, Glass','7','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Beverage Dispenser, Plastic, 3.5 Gal','2','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Ice Bowl','67','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Ice Bowl, Metal Revere','6','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Pitcher, Glass','7','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Pitcher, Plastic Amber','80','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Pitcher, Plastic Clear','87','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Beverage Service','Pitcher, Stainless Steel','52','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Carving Board, Large','15','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Carving Board, Small','9','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Carving Fork','15','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Carving Knife','28','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Chafer,  3 Qt with Insert','74','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Chafer, 2 Gal with Insert','16','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Chafer, Insert 2 Gal','75','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Risers, Cake','12','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Risers, Silver','76','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Sterno Grill, 2 Gal','10','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Three Tier Stand w/ 14" Platters','20','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Buffet Equipment','Two Tier Stand w/ 14" Platters','18','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','AD Cup','379','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','AD Cup w/ Saucer','904','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Coffee Creamer','90','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Coffee Cup','1328','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Coffee Saucer ','1408','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, B/B','3117','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Dessert','150','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Dinner','992','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Dinner Clear','144','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Salad','1822','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Salad ','1704','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Soup','755','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Square B/B','106','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','China','Plate, Square Dessert ','237','0.0','0.0','                                                                                                                                                                                                                                                              ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Coffee Pots - Air Voids, 10ppl','42','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Coffee Pots, 50ppl','16','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Coffee Pots, 8ppl','63','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Coffee Sugar Container','95','0.0','0.0','For Coffee Sweeteners',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Samovar, Silver Service','27','0.0','0.0','                                                                                                                                            ',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Silver Square Tray - Coffee','20','0.0','0.0','For Coffee Service',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Coffee Service','Silver Sugar Tray ','20','0.0','0.0','For Coffee Service',null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Butter Knives, Silverware','610','0.0','0.0',null,null,null,null,null,null);
Insert into SAMPLE_EQUIPMENT (CATEGORY,SUBCATEGORY,NAMEE,QUANTITY,PRICE,COSTV,COMMENTS,SCALABLE,QTYPERPERSON,SORTORDER,PLATTER,ACTIVE) values ('CH','Flatware','Dinner Fork, Stainless Steel','2830','0.0','0.0',null,null,null,null,null,null);

delete from sample_equipment where rowid not in
(select max(rowid) from sample_equipment   group by trim(namee), subcategory);

Declare
   lcatid   NUMBER DEFAULT NULL;
   lscatid  number  default null;
BEGIN
   FOR DATA IN (SELECT * FROM sample_equipment )
   LOOP
      BEGIN
         SELECT ID
           INTO lcatid
           FROM equipmentcategory
          WHERE LOWER (CATEGORY) = LOWER (data.CATEGORY);
      EXCEPTION
         WHEN NO_DATA_FOUND
         THEN
         
            INSERT INTO equipmentcategory
                        (ID, active, CATEGORY
                        )
                 VALUES (equipmentcategory_pk_seq.NEXTVAL, 1, DATA.CATEGORY
                        );
        select equipmentcategory_pk_seq.currVAL into lcatid from dual;
      END;
      BEGIN
         SELECT ID
           INTO lscatid
           FROM equipmentsubcategory
          WHERE equipmentcategory_id = lcatid
          and LOWER (SubCATEGORY) = LOWER (data.subCATEGORY);
      EXCEPTION
         WHEN NO_DATA_FOUND
         THEN
         
            INSERT INTO equipmentsubcategory
                        (ID, active, EquipmentCATEGORY_id,subcategory
                        )
                 VALUES (equipmentsubcategory_pk_seq.NEXTVAL, 1, lcatid,data.subcategory
                        );
        select equipmentsubcategory_pk_seq.currVAL into lscatid from dual;
      END;
      INSERT INTO equipment
                        (ID, active,
                         equipmentsubcategory_id, NAME,
                         COST, comments, ourcost,platter,Quantity, Scalable, Qty_per_person, sortorder
                        )
                 VALUES (equipment_pk_seq.NEXTVAL, 1,
                       lscatid, substr(trim(DATA.namee),1,50),
                         DATA.price, DATA.comments,DATA.COSTV,data.platter,data.quantity, data.scalable, data.QtyPerPerson, data.SortOrder
                        ); 
     
   END LOOP;
COMMIT;
  
END;
/
